<a href="https://colab.research.google.com/github/divate11-rgb/Python_Practice_Assignment14052026/blob/master/Assignment14052026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
df = pd.read_excel('sample_data.xlsx')
df[:]

,age,job,id,education,edu_num,marrital_status,post,family,race,gender,captial_gain,num,value,country,inome
0,39,state-gov,77516,bachelors,13,never-married,adm-clerical,not-in-family,white,male,2174,0,40,united-states,<=50k
1,50,self-emp-not-inc,83311,bachelors,13,married-civ-spouse,exec-managerial,husband,white,male,0,0,13,united-states,<=50k
2,38,private,215646,hs-grad,9,divorced,handlers-cleaners,not-in-family,white,male,0,0,40,united-states,<=50k
3,53,private,234721,11th,7,married-civ-spouse,handlers-cleaners,husband,black,male,0,0,40,united-states,<=50k
4,28,private,338409,bachelors,13,married-civ-spouse,prof-specialty,wife,black,female,0,0,40,cuba,<=50k
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,private,257302,assoc-acdm,12,married-civ-spouse,tech-support,wife,white,female,0,0,38,united-states,<=50k
32557,40,private,154374,hs-grad,9,married-civ-spouse,machine-op-inspct,husband,white,male,0,0,40,united-states,>50k
32558,58,private,151910,hs-grad,9,widowed,adm-clerical,unmarried,white,female,0,0,40,united-states,<=50k
32559,22,private,201490,hs-grad,9,never-married,adm-clerical,own-child,white,male,0,0,20,united-states,<=50k
32560,52,self-emp-inc,287927,hs-grad,9,married-civ-spouse,exec-managerial,wife,white,female,15024,0,40,united-states,>50k

In [5]:
#Assignment: Filtering Data with query()
#Fetch all records where the education is 'bachelors' and the gender is 'female'.

df.query('education=="bachelors" and gender=="female"')

,age,job,id,education,edu_num,marrital_status,post,family,race,gender,captial_gain,num,value,country,inome
4,28,private,338409,bachelors,13,married-civ-spouse,prof-specialty,wife,black,female,0,0,40,cuba,<=50k
12,23,private,122272,bachelors,13,never-married,adm-clerical,own-child,white,female,0,0,30,united-states,<=50k
71,31,private,309974,bachelors,13,separated,sales,own-child,black,female,0,0,40,united-states,<=50k
125,47,private,287828,bachelors,13,married-civ-spouse,exec-managerial,wife,white,female,0,0,40,united-states,>50k
152,33,private,163003,bachelors,13,never-married,exec-managerial,other-relative,asian-pac-islander,female,0,0,40,philippines,<=50k
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32511,25,local-gov,514716,bachelors,13,never-married,adm-clerical,own-child,black,female,0,0,40,united-states,<=50k
32530,35,?,320084,bachelors,13,married-civ-spouse,?,wife,white,female,0,0,55,united-states,>50k
32531,30,?,33811,bachelors,13,never-married,?,not-in-family,asian-pac-islander,female,0,0,99,united-states,<=50k
32536,34,private,160216,bachelors,13,never-married,exec-managerial,not-in-family,white,female,0,0,55,united-states,>50k
32538,38,private,139180,bachelors,13,divorced,prof-specialty,unmarried,black,female,15020,0,45,united-states,>50k

In [6]:
#Assignment: Creating a New Column with apply()
#Create a new column named income_level. Use the apply() function on the inome column. If inome is '<=50k',
#the income_level should be 'low_income'; otherwise, it should be 'high_income'.
#df['inome'].unique()
df['income_level'] = df['inome'].apply(lambda inome:'low_income' if inome=='<=50k' else 'high_income')
df[:20]

,age,job,id,education,edu_num,marrital_status,post,family,race,gender,captial_gain,num,value,country,inome,income_level
0,39,state-gov,77516,bachelors,13,never-married,adm-clerical,not-in-family,white,male,2174,0,40,united-states,<=50k,low_income
1,50,self-emp-not-inc,83311,bachelors,13,married-civ-spouse,exec-managerial,husband,white,male,0,0,13,united-states,<=50k,low_income
2,38,private,215646,hs-grad,9,divorced,handlers-cleaners,not-in-family,white,male,0,0,40,united-states,<=50k,low_income
3,53,private,234721,11th,7,married-civ-spouse,handlers-cleaners,husband,black,male,0,0,40,united-states,<=50k,low_income
4,28,private,338409,bachelors,13,married-civ-spouse,prof-specialty,wife,black,female,0,0,40,cuba,<=50k,low_income
5,37,private,284582,masters,14,married-civ-spouse,exec-managerial,wife,white,female,0,0,40,united-states,<=50k,low_income
6,49,private,160187,9th,5,married-spouse-absent,other-service,not-in-family,black,female,0,0,16,jamaica,<=50k,low_income
7,52,self-emp-not-inc,209642,hs-grad,9,married-civ-spouse,exec-managerial,husband,white,male,0,0,45,united-states,>50k,high_income
8,31,private,45781,masters,14,never-married,prof-specialty,not-in-family,white,female,14084,0,50,united-states,>50k,high_income
9,42,private,159449,bachelors,13,married-civ-spouse,exec-managerial,husband,white,male,5178,0,40,united-states,>50k,high_income
10,37,private,280464,some-college,10,married-civ-spouse,exec-managerial,husband,black,male,0,0,80,united-states,>50k,high_income
11,30,state-gov,141297,bachelors,13,married-civ-spouse,prof-specialty,husband,asian-pac-islander,male,0,0,40,india,>50k,high_income
12,23,private,122272,bachelors,13,never-married,adm-clerical,own-child,white,female,0,0,30,united-states,<=50k,low_income
13,32,private,205019,assoc-acdm,12,never-married,sales,not-in-family,black,male,0,0,50,united-states,<=50k,low_income
14,40,private,121772,assoc-voc,11,married-civ-spouse,craft-repair,husband,asian-pac-islander,male,0,0,40,?,>50k,high_income
15,34,private,245487,7th-8th,4,married-civ-spouse,transport-moving,husband,amer-indian-eskimo,male,0,0,45,mexico,<=50k,low_income
16,25,self-emp-not-inc,176756,hs-grad,9,never-married,farming-fishing,own-child,white,male,0,0,35,united-states,<=50k,low_income
17,32,private,186824,hs-grad,9,never-married,machine-op-inspct,unmarried,white,male,0,0,40,united-states,<=50k,low_income
18,38,private,28887,11th,7,married-civ-spouse,sales,husband,white,male,0,0,50,united-states,<=50k,low_income
19,43,self-emp-not-inc,292175,masters,14,divorced,exec-managerial,unmarried,white,female,0,0,45,united-states,>50k,high_income

In [7]:
#Assignment: Filtering Data with query() - Part 2
#Find all records where the job is 'private' and marrital_status is 'married-civ-spouse'.
df.query('job=="private" and marrital_status=="married-civ-spouse"')

,age,job,id,education,edu_num,marrital_status,post,family,race,gender,captial_gain,num,value,country,inome,income_level
3,53,private,234721,11th,7,married-civ-spouse,handlers-cleaners,husband,black,male,0,0,40,united-states,<=50k,low_income
4,28,private,338409,bachelors,13,married-civ-spouse,prof-specialty,wife,black,female,0,0,40,cuba,<=50k,low_income
5,37,private,284582,masters,14,married-civ-spouse,exec-managerial,wife,white,female,0,0,40,united-states,<=50k,low_income
9,42,private,159449,bachelors,13,married-civ-spouse,exec-managerial,husband,white,male,5178,0,40,united-states,>50k,high_income
10,37,private,280464,some-college,10,married-civ-spouse,exec-managerial,husband,black,male,0,0,80,united-states,>50k,high_income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32551,32,private,34066,10th,6,married-civ-spouse,handlers-cleaners,husband,amer-indian-eskimo,male,0,0,40,united-states,<=50k,low_income
32552,43,private,84661,assoc-voc,11,married-civ-spouse,sales,husband,white,male,0,0,45,united-states,<=50k,low_income
32554,53,private,321865,masters,14,married-civ-spouse,exec-managerial,husband,white,male,0,0,40,united-states,>50k,high_income
32556,27,private,257302,assoc-acdm,12,married-civ-spouse,tech-support,wife,white,female,0,0,38,united-states,<=50k,low_income
32557,40,private,154374,hs-grad,9,married-civ-spouse,machine-op-inspct,husband,white,male,0,0,40,united-states,>50k,high_income

In [8]:
#Assignment: Exploring Unique Values
#Find all unique country values in the dataset
df['country'].unique()

array(['united-states', 'cuba', 'jamaica', 'india', '?', 'mexico',
       'south', 'puerto-rico', 'honduras', 'england', 'canada', 'germany',
       'iran', 'philippines', 'italy', 'poland', 'columbia', 'cambodia',
       'thailand', 'ecuador', 'laos', 'taiwan', 'haiti', 'portugal',
       'dominican-republic', 'el-salvador', 'france', 'guatemala',
       'china', 'japan', 'yugoslavia', 'peru',
       'outlying-us(guam-usvi-etc)', 'scotland', 'trinadad&tobago',
       'greece', 'nicaragua', 'vietnam', 'hong', 'ireland', 'hungary',
       'holand-netherlands'], dtype=object)

In [9]:
#Assignment: Filtering by Numerical Condition
#Select all rows where age is greater than 60.
df.query('age>60')

,age,job,id,education,edu_num,marrital_status,post,family,race,gender,captial_gain,num,value,country,inome,income_level
74,79,private,124744,some-college,10,married-civ-spouse,prof-specialty,other-relative,white,male,0,0,20,united-states,<=50k,low_income
77,67,?,212759,10th,6,married-civ-spouse,?,husband,white,male,0,0,2,united-states,<=50k,low_income
100,76,private,124191,masters,14,married-civ-spouse,exec-managerial,husband,white,male,0,0,40,united-states,>50k,high_income
140,61,self-emp-inc,66614,hs-grad,9,married-civ-spouse,craft-repair,husband,white,male,0,0,40,united-states,<=50k,low_income
144,70,private,105376,some-college,10,never-married,tech-support,other-relative,white,male,0,0,40,united-states,<=50k,low_income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32515,66,federal-gov,47358,10th,6,married-civ-spouse,craft-repair,husband,white,male,3471,0,40,united-states,<=50k,low_income
32525,81,?,120478,assoc-voc,11,divorced,?,unmarried,white,female,0,0,1,?,<=50k,low_income
32539,71,?,287372,doctorate,16,married-civ-spouse,?,husband,white,male,0,0,10,united-states,>50k,high_income
32542,72,?,129912,hs-grad,9,married-civ-spouse,?,husband,white,male,0,0,25,united-states,<=50k,low_income
32548,65,self-emp-not-inc,99359,prof-school,15,never-married,prof-specialty,not-in-family,white,male,1086,0,60,united-states,<=50k,low_income

In [10]:
#Assignment: Creating a Column with apply() based on capital_gain
#Create a new column called has_capital_gain. If captial_gain is greater than 0, set has_capital_gain to 1,
# otherwise set it to 0.
#df['captial_gain'].unique()
df['has_capital_gain'] = df['captial_gain'].apply(lambda captial_gain: '1' if captial_gain > 0 else '0')
df[:2]

,age,job,id,education,edu_num,marrital_status,post,family,race,gender,captial_gain,num,value,country,inome,income_level,has_capital_gain
0,39,state-gov,77516,bachelors,13,never-married,adm-clerical,not-in-family,white,male,2174,0,40,united-states,<=50k,low_income,1
1,50,self-emp-not-inc,83311,bachelors,13,married-civ-spouse,exec-managerial,husband,white,male,0,0,13,united-states,<=50k,low_income,0

In [11]:
#Assignment: Further Cleaning - Handling '?' values
#Identify all columns that contain '?' values and replace these '?' with 'unknown'.
df = df.replace('?','unknown')
df[:]

,age,job,id,education,edu_num,marrital_status,post,family,race,gender,captial_gain,num,value,country,inome,income_level,has_capital_gain
0,39,state-gov,77516,bachelors,13,never-married,adm-clerical,not-in-family,white,male,2174,0,40,united-states,<=50k,low_income,1
1,50,self-emp-not-inc,83311,bachelors,13,married-civ-spouse,exec-managerial,husband,white,male,0,0,13,united-states,<=50k,low_income,0
2,38,private,215646,hs-grad,9,divorced,handlers-cleaners,not-in-family,white,male,0,0,40,united-states,<=50k,low_income,0
3,53,private,234721,11th,7,married-civ-spouse,handlers-cleaners,husband,black,male,0,0,40,united-states,<=50k,low_income,0
4,28,private,338409,bachelors,13,married-civ-spouse,prof-specialty,wife,black,female,0,0,40,cuba,<=50k,low_income,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,private,257302,assoc-acdm,12,married-civ-spouse,tech-support,wife,white,female,0,0,38,united-states,<=50k,low_income,0
32557,40,private,154374,hs-grad,9,married-civ-spouse,machine-op-inspct,husband,white,male,0,0,40,united-states,>50k,high_income,0
32558,58,private,151910,hs-grad,9,widowed,adm-clerical,unmarried,white,female,0,0,40,united-states,<=50k,low_income,0
32559,22,private,201490,hs-grad,9,never-married,adm-clerical,own-child,white,male,0,0,20,united-states,<=50k,low_income,0
32560,52,self-emp-inc,287927,hs-grad,9,married-civ-spouse,exec-managerial,wife,white,female,15024,0,40,united-states,>50k,high_income,1