<a href="https://colab.research.google.com/github/divate11-rgb/Python_Practice_Assignment14052026/blob/master/Student_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
# Import necessary libraries
import pandas as pd
import numpy as np

# Read First Sheet from the Student Data file
#Student_Info = pd.read_excel('CandidateTestData_pandas.xlsx',sheet_name='Sheet1')
#Student_Info[:]

# Read Second Sheet from the Student Data file
#Subject_Info = pd.read_excel('CandidateTestData_pandas.xlsx',sheet_name='Sheet2')
#Subject_Info[:]

# Revert column values of column Roll No
#Subject_Info['ReversedRollNo'] = Subject_Info['ReversedRollNo'].str[::-1]

# Update column name in Subject_Info data sheet
#Subject_Info.rename(columns={'ReversedRollNo':'RollNo'},inplace=True)

# Merge 2 data sheets into single data sheet
#Student_Data = pd.merge(Student_Info,Subject_Info,on='RollNo',how='left')

# Generate combine excel file
#Student_Data.to_excel('Student_Data.xlsx',index=False)

# Read combined data file
#sd = pd.read_excel('Student_Data.xlsx')

# Replace all NaN values fromm all cells to zero
#sd1 = sd.fillna(0)

# Download Final Data file
#sd1.to_excel('Student_Data_Combined.xlsx',index=False)

# Read final data file
std = pd.read_excel('Student_Data_Combined.xlsx')
std

    RollNo       Name Section  Maths  English  Physics  Chemistry
0   RO1001   student1       C     63        7        3         62
1   RO1002   student2       A     20       97        4         46
2   RO1003   student3       A     84       45        6         56
3   RO1004   student4       A     54       12        0         32
4   RO1005   student5       C     39        6       80         62
..     ...        ...     ...    ...      ...      ...        ...
94  RO1095  student95       C     81       38        0          0
95  RO1096  student96       A     92       40        2         32
96  RO1097  student97       C     89       80       44         76
97  RO1098  student98       A     43       63       80         39
98  RO1099  student99       B     23       16        0          0

[99 rows x 7 columns]

In [63]:
#Calculate Total: Create a new column named Total_Marks that sums up the scores of all subjects for each student.
#std['Total_Marks'] = std.query('Maths'+'English'+'Physics'+'Chemistry')
std.eval('Total_Marks = Maths + English + Physics + Chemistry', inplace=True)
std

    RollNo       Name Section  Maths  English  Physics  Chemistry  Total_Marks
0   RO1001   student1       C     63        7        3         62          135
1   RO1002   student2       A     20       97        4         46          167
2   RO1003   student3       A     84       45        6         56          191
3   RO1004   student4       A     54       12        0         32           98
4   RO1005   student5       C     39        6       80         62          187
..     ...        ...     ...    ...      ...      ...        ...          ...
94  RO1095  student95       C     81       38        0          0          119
95  RO1096  student96       A     92       40        2         32          166
96  RO1097  student97       C     89       80       44         76          289
97  RO1098  student98       A     43       63       80         39          225
98  RO1099  student99       B     23       16        0          0           39

[99 rows x 8 columns]

In [64]:
#Calculate Percentage: Create a new column named Percentage. (Assume the maximum score for each subject is 100).

std['Percentage'] = (std['Total_Marks']/400) *100
std

,RollNo,Name,Section,Maths,English,Physics,Chemistry,Total_Marks,Percentage
0,RO1001,student1,C,63,7,3,62,135,33.75
1,RO1002,student2,A,20,97,4,46,167,41.75
2,RO1003,student3,A,84,45,6,56,191,47.75
3,RO1004,student4,A,54,12,0,32,98,24.50
4,RO1005,student5,C,39,6,80,62,187,46.75
...,...,...,...,...,...,...,...,...,...
94,RO1095,student95,C,81,38,0,0,119,29.75
95,RO1096,student96,A,92,40,2,32,166,41.50
96,RO1097,student97,C,89,80,44,76,289,72.25
97,RO1098,student98,A,43,63,80,39,225,56.25
98,RO1099,student99,B,23,16,0,0,39,9.75

In [73]:
#Identify Top Performers: Display the data for the top 3 students based on their Percentage.
std.sort_values(by='Percentage',ascending=False,inplace=True)
std[:3]

,RollNo,Name,Section,Maths,English,Physics,Chemistry,Total_Marks,Percentage
27,RO1028,student28,A,83,83,99,82,347,86.75
6,RO1007,student7,C,84,79,99,84,346,86.50
32,RO1033,student33,C,82,98,87,63,330,82.50

In [110]:
#Section Analysis: Calculate and print the average percentage for each Section
 #(e.g., Average percentage of Section A vs. Section B).

Total_Percentage_A = std.loc[std['Section'] == 'A', 'Percentage'].sum()
print("Sum Of Percentage of Section A is: ",Total_Percentage_A)
Section_A= (std['Section']=='A').sum()
print("Total sum of Section A is: ",Section_A)
A_Average = Total_Percentage_A/Section_A
print("Average Percentage Of Section A is: ",A_Average)

Total_Percentage_B = std.loc[std['Section'] == 'B', 'Percentage'].sum()
print("Sum Of Percentage of Section B is: ",Total_Percentage_B)
Section_B= (std['Section']=='B').sum()
print("Total sum of Section B is: ",Section_B)
B_Average = Total_Percentage_B/Section_B
print("Average Percentage Of Section B is: ",B_Average)

Total_Percentage_C = std.loc[std['Section'] == 'C', 'Percentage'].sum()
print("Sum Of Percentage of Section C is: ",Total_Percentage_C)
Section_C= (std['Section']=='C').sum()
print("Total sum of Section C is: ",Section_C)
C_Average = Total_Percentage_C/Section_C
print("Average Percentage Of Section C is: ",C_Average)

Sum Of Percentage of Section A is:  1458.25
Total sum of Section A is:  33
Average Percentage Of Section A is:  44.18939393939394
Sum Of Percentage of Section B is:  900.0
Total sum of Section B is:  25
Average Percentage Of Section B is:  36.0
Sum Of Percentage of Section C is:  1829.75
Total sum of Section C is:  41
Average Percentage Of Section C is:  44.6280487804878